### ISSUE TITLE
Send end status after 03:30

### ISSUE THREAD

**Issue by poka-IT** [physia/kflutter#13]
Strange bug, but in network playing, with audioplayer version, when I set the position after 03:30 of a track, even this track is 5 minutes or more, it will send a end status and stop.

**Comment by mohamadlounnas** [comment]
Unfortunately this is a issue with audioplayer
I tried to find a solution for it but a part of C++ code is behaving strangely `SeekTo(uint64_t position)`
after 210 second when position passed to `SeekTo(uint64_t position)` the number be something different (exactly a very big integer)

**Comment by mohamadlounnas** [comment]
@poka-IT 
currently you can use this
thanks to [maintel](https://github.com/maintel)
```yaml
dependency_overrides:
  audioplayers_windows:
    git:
      url: https://github.com/kflutter/audioplayers
      path: packages/audioplayers_windows
      ref: 263b4cc648d39a79455c221897a2c699f9d1c4c0
```
audioplayers know in the main package.
